name: workflow
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # Ignores pip warnings about running as root
      PIP_ROOT_USER_ACTION: ignore
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1-mesa libgl1-mesa-dev libglib2.0-0 \
              libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 \
              libxcb-render-util0 libxcb-xfixes0 libxcb-xinerama0 \
              libxkbcommon-x11-0 x11-utils xvfb

      - name: Sets up Virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install pyqt6 pytest pytest-qt
          pip install -r requirements.txt

      - name: Run pytest with Xvfb
        env:
          QT_QPA_PLATFORM: offscreen
        run: |
          xvfb-run pytest -v
