# Action which runs the pytest unit tests
name: Pytest Unit Testing
on: [push]
permissions:
  # Access to check-out code and install dependencies for f.ex. setup-python
  contents: read
jobs:
  test:
    # ubuntu-latest (24.04) does not support all required packages
    runs-on: ubuntu-22.04
    env:
      # Ignores pip warnings about running as root
      # Not *best* practice, but I do not predict this to betray us
      PIP_ROOT_USER_ACTION: ignore

    steps:
      - name: Check-out repo so the workflow can access it
        uses: actions/checkout@v4

      - name: Install Python and add it to PATH
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          # Caches pip dependencies
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1-mesa libgl1-mesa-dev libglib2.0-0 \
              libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 \
              libxcb-render-util0 libxcb-xfixes0 libxcb-xinerama0 \
              libxkbcommon-x11-0 x11-utils xvfb

      - name: Set up Python virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt6 pytest pytest-qt
          pip install -r requirements.txt

      - name: Run pytest through Xvfb
        env:
          QT_QPA_PLATFORM: offscreen
        run: xvfb-run pytest -v
