# Workflow which runs tests and lints for a single python version

name: flake8 and pytest

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11  # We can use a matrix to test for multiple python versions
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pyqt6  # Installs flake8 for relevant python version
        pip install -r requirements.txt
    - name: Lint with flake8
      run: flake8
    - name: Test with pytest
      run: pytest
