# Action which runs the pytest unit tests
name: Pytest Unit Testing
on: [push]
permissions:
  # Access to check-out code and install dependencies for f.ex. setup-python
  contents: read
jobs:
  test:
    # ubuntu-latest (24.04) does not support all required packages
    runs-on: ubuntu-22.04
    env:
      # Ignores pip warnings about running as root
      # Not *best* practice, but I do not predict this to betray us
      PIP_ROOT_USER_ACTION: ignore

    steps:
      - name: CHECK-OUT REPO SO THE WORKFLOW CAN ACCESS IT
        uses: actions/checkout@v4

      - name: INSTALL/CACHE APT PACKAGES
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libegl1-mesa libgl1-mesa-dev libglib2.0-0 libxcb-icccm4 \
            libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 \
            libxcb-xfixes0 libxcb-xinerama0 libxkbcommon-x11-0 x11-utils xvfb

      - name: INSTALL PYTHON AND ADD IT TO PATH
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          # Caches pip dependencies
          cache: 'pip'

      - name: SET UP PYTHON VIRTUAL ENVIRONMENT
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: INSTALL PYTHON DEPENDENCIES
        run: |
          python -m pip install --upgrade pip
          pip install pyqt6 pytest pytest-qt flake8
          pip install -r requirements.txt

      - name: RUN PYTEST THROUGH XVFB
        env:
          QT_QPA_PLATFORM: offscreen
        run: xvfb-run pytest -v

      # Configuration found in file '.flake8'
      - name: LINT WITH FLAKE8
        # Runs as a python module so we can specify the version number
        # --statistics makes a tally of which errors were triggered
        # --exit-zero  returns positive, so the workflow doesn't fail just for this
        run: python3.11 -m flake8 --statistics --exit-zero
